import { execFileSync } from 'node:child_process';
import { createHash, randomUUID } from 'node:crypto';
import { AwsClient } from 'aws4fetch';
import { accessToken, api } from './api';

/** MEDIA fixtures generated by the worker's synthetic helpers (no real photos). */
export function mediaFixtures(): Record<'png' | 'jpegOriented' | 'heic' | 'webp' | 'animatedWebp', Buffer> {
  const script = `
import base64, json
from tests.conftest import animated, encode, jpeg_with_orientation_and_gps, two_tone
print(json.dumps({k: base64.b64encode(v).decode() for k, v in {
  "png": encode(two_tone(), "PNG"),
  "jpegOriented": jpeg_with_orientation_and_gps(6),
  "heic": encode(two_tone(), "HEIF"),
  "webp": encode(two_tone(), "WEBP"),
  "animatedWebp": animated("WEBP"),
}.items()}))`;
  const output = execFileSync('uv', ['run', 'python', '-c', script], { cwd: 'services/worker', encoding: 'utf8' });
  return Object.fromEntries(Object.entries(JSON.parse(output)).map(([k, v]) => [k, Buffer.from(v as string, 'base64')])) as never;
}

export const sha256 = (bytes: Uint8Array) => createHash('sha256').update(bytes).digest('hex');

/** Storage access for assertions only (object existence), using local credentials. */
export function storageAdmin() {
  const aws = new AwsClient({
    accessKeyId: 'local-storage-access-key',
    secretAccessKey: 'local-storage-secret-key-0123456789abcdef',
    service: 's3',
    region: 'auto',
  });
  const url = (key: string) => `http://127.0.0.1:9000/bowr-private/${key}`;
  return {
    exists: async (key: string) => (await aws.fetch(url(key), { method: 'HEAD' })).status === 200,
    get: async (key: string) => Buffer.from(await (await aws.fetch(url(key))).arrayBuffer()),
  };
}

export type Member = { id: string; email: string; token: string };

export async function member(createIdentity: (label: string) => Promise<{ id: string; email: string }>, label: string): Promise<Member> {
  const identity = await createIdentity(label);
  return { ...identity, token: await accessToken(identity.email) };
}

/** Creates a one-file batch through the public API. */
export async function createSlot(token: string, bytes: Buffer, contentType: string, key = randomUUID()) {
  const response = await api('/upload-batches', {
    token,
    method: 'POST',
    key,
    body: { files: [{ client_file_id: randomUUID(), purpose: 'garment', content_type: contentType, byte_size: bytes.length }] },
  });
  if (response.status !== 201) throw new Error(`batch ${response.status} ${JSON.stringify(response.body)}`);
  return { batchId: response.body.data.batch_id as string, entry: response.body.data.entries[0], raw: response };
}

export async function putSlot(entry: { upload: { url: string; headers: Record<string, string> } }, bytes: Buffer) {
  return fetch(entry.upload.url, { method: 'PUT', headers: entry.upload.headers, body: bytes });
}

/**
 * WARDROBE photo fixtures, generated synthetically by the worker's helpers:
 * a shirt and trousers on a plain background, and a blank photo in which no garment can be found. No real photos are committed.
 */
export function wardrobeFixtures(): Record<'garment' | 'trousers' | 'blank', Buffer> {
  const script = `
import base64, json
from PIL import Image
from tests.conftest import encode, garment, trousers
print(json.dumps({k: base64.b64encode(v).decode() for k, v in {
  "garment": encode(garment(), "PNG"),
  "trousers": encode(trousers(), "PNG"),
  "blank": encode(Image.new("RGB", (640, 480), (200, 200, 200)), "PNG"),
}.items()}))`;
  const output = execFileSync('uv', ['run', 'python', '-c', script], { cwd: 'services/worker', encoding: 'utf8' });
  return Object.fromEntries(Object.entries(JSON.parse(output)).map(([k, v]) => [k, Buffer.from(v as string, 'base64')])) as never;
}
